[package]
name = "fantasy_f1"
version = "1.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
termion = "1.5.6"
combinations = "0.1.0"

